### ISSUE TITLE
Improve FloatingActionMenu

### ISSUE THREAD

**Issue by taltstidl** [TR4Android/AppCompat-Extension-Library#14]
Any other suggestions for improving the `FloatingActionMenu`? Feel free to comment below!

**Checklist for Release 0.4.0:**
- [x] The animation isn't quite the same as the [Speed dial](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-Znh2YWx1VnE3NEk/components-buttons-fab-transition_speeddial_01.mp4) presented in the Material Design Guidelines 
- [x] The labels should have elevation and state support (along with `show` and `hide()` methods for animation purposes), this will probably result in a new `LabelView`
- [x] The `RotationTransitionDrawable` should also rotate pre-Honeycomb with the help of the new `ValueAnimatorCompat`
- [x] The attributes should include one which allows you to customize the distance between buttons

**Comment by sedestrian** [comment]
You could make an option to choose the distance between the menu buttons, that would be helpful :)

**Comment by taltstidl** [comment]
@sedestrian Good idea! Added it to the list.

**Comment by sedestrian** [comment]
Great!

**Comment by taltstidl** [comment]
@sedestrian You can now customize the button spacing in release `0.3.0` by using the `app:fabMenuSpacing` attribute. Thanks for the patience!

**Comment by athospg** [comment]
The visibility should be changed to "INVISIBLE" instead of "GONE". The top FAB label is still visible if GONE is used.
![device-2016-04-26-162212](https://cloud.githubusercontent.com/assets/6840773/14831316/999f8e88-0bcb-11e6-9d5b-85f25f7b2663.png)

**Comment by taltstidl** [comment]
@athospg Thanks, I'm aware of this :smiley:, this is currently a work in progress (I'm currently working on the `LabelView`, after that is finished this issue should be gone).

**Comment by taltstidl** [comment]
All features here are now implemented and will be released as part of Release 0.4.0 by the end of next week, so I'll be closing this issue now.
