### ISSUE TITLE
Subtitle of FlexibleToolbarLayout is not getting styled.

### ISSUE THREAD

**Issue by ApplicationNinja** [TR4Android/AppCompat-Extension-Library#15]
Lines #246 - #256 of FlexibleToolbarLayout.java are incorrect, in that they read the sub title style, but apply it to the title instead of the subtitle.

**Comment by taltstidl** [comment]
@TechnologySolutionsGroup Good catch, thanks for the investigation! :+1:

**Comment by ApplicationNinja** [comment]
Sorry, need to re-open, lines #249 and #254 need to be changed too, otherwise you're applying the title style to the sub title element. :)

**Comment by taltstidl** [comment]
@TechnologySolutionsGroup Shoot, I should have paid more attention! Thanks :smile:

**Comment by taltstidl** [comment]
@TechnologySolutionsGroup Release `0.3.0` contains this fix, so you can update to it if you want to. Thanks again! :smiley:
