### ISSUE TITLE
FAB clicks with FAM closed

### ISSUE THREAD

**Issue by athospg** [TR4Android/AppCompat-Extension-Library#18]
While the FAM is closed the first FAB can be clicked on the left side of the FAM.

**Comment by taltstidl** [comment]
@athospg Thanks, I'll take a look at this. What Android version are you experiencing this on?

**Comment by athospg** [comment]
@TR4Android I'm using CM12.1 (Android 5.1.1). To test that you have to change the sample to handle clicks on the FABs.

**Comment by taltstidl** [comment]
Fixed with commit 9433374d4bf46e5678e8ca5952aa7b7781802987 (also adds a few additional features as outlined in issue #14). Thanks for your contributions! Release 0.4.0 will be out by the end of next week.
