### ISSUE TITLE
FlexibleToolbarLayout icon load by glide

### ISSUE THREAD

**Issue by JasonHezz** [TR4Android/AppCompat-Extension-Library#26]
Currently I want to set a url img as a icon,unfortunately it's not a imgeview,How can I do this?

**Comment by taltstidl** [comment]
@JasonHezz Though I have not used Glide with the `FlexibleToolbarLayout` yet, you should be able to make use of the [Custom targets](https://github.com/bumptech/glide/wiki/Custom-targets) provided by Glide. How exactly this should be used depends on what you're trying to achieve.
Let me know if I can be of further assistance!

**Comment by JasonHezz** [comment]
Sorry for late reply due to Chinese New Year...Your solution works.Thank you .
